name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard_index: [1, 2, 3]
    name: Test (shard ${{ matrix.shard_index }}/3)

    steps:
      - uses: actions/checkout@v4

      - name: Checkout smart-tests-cli
        uses: actions/checkout@v4
        with:
          repository: cloudbees-oss/smart-tests-cli
          ref: feature/AIENG-624-CLI-Add-from-github-actions-option-to-Subset-command
          path: smart-tests-cli

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Set up smart-tests CLI
        run: pip install ./smart-tests-cli

      - name: Run Test with Smart Tests
        env:
          SMART_TESTS_TOKEN: "v1:cloudbees/urr:28a1ce00db724460a605f89dba91273a"
          SMART_TESTS_BASE_URL: "https://elusive-mustiness-gone.ngrok-free.dev"
        run: |
          smart-tests subset --from-github-actions maven --target 80% --bin ${{ matrix.shard_index }}/3 src/test/java > subset.txt
          echo "=== Subset tests ==="
          cat subset.txt
          mvn test -Dsurefire.includesFile=subset.txt

      - name: Print runner details
        if: always()
        run: |
          echo "Runner Name: $RUNNER_NAME"
          echo "Runner OS: $RUNNER_OS"
          echo "Runner Arch: $RUNNER_ARCH"
          echo "Run ID: $GITHUB_RUN_ID"
          echo "Run Attempt: $GITHUB_RUN_ATTEMPT"
          echo "Job: $GITHUB_JOB"

      - name: Store Test Results for Smart Tests
        if: always()
        uses: cloudbees-oss/smart-tests-results-upload-action@v1
